CREATE TABLE PLAYER
(
    id IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL,
    url VARCHAR NOT NULL,
    score SMALLINT NOT NULL DEFAULT 100,
    won SMALLINT NOT NULL DEFAULT 0,
    lost SMALLINT NOT NULL DEFAULT 0
);